version: '3'

services:
  app:
    container_name: app
    image: django-tutorial:dev
    build:
      context: .
      dockerfile: Dockerfile.django
    command: gunicorn --bind 0:8000 mysite.wsgi

  server:
    container_name: nginx
    image: django-tutorial:server
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - app
    ports:
      - 80:80
