FROM python:3.9.12-slim-bullseye
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY app .

RUN python manage.py migrate

EXPOSE 8000
CMD ["python","manage.py","runserver","0:8000","--noreload"]
